import type { BreedInfo, Species, PetSize, ActivityLevel } from "@/types"

export const DOG_BREEDS: BreedInfo[] = [
  {
    breed: "말티즈",
    species: "dog",
    avgWeight: { min: 2, max: 4 },
    avgLifespan: { min: 12, max: 15 },
    size: "small",
    commonHealthIssues: ["슬개골 탈구", "기관허탈", "치과 질환", "눈물자국"],
    geneticConditions: ["백내장", "심장병"],
    exerciseNeeds: "moderate",
    groomingNeeds: "high",
    dietaryConsiderations: ["소형견용 작은 알갱이", "치석 관리"],
  },
  {
    breed: "푸들",
    species: "dog",
    avgWeight: { min: 3, max: 6 },
    avgLifespan: { min: 12, max: 15 },
    size: "small",
    commonHealthIssues: ["슬개골 탈구", "치과 질환", "귀 감염"],
    geneticConditions: ["진행성 망막 위축", "폰빌레브란트병"],
    exerciseNeeds: "moderate",
    groomingNeeds: "high",
    dietaryConsiderations: ["알레르기 주의"],
  },
  {
    breed: "시츄",
    species: "dog",
    avgWeight: { min: 4, max: 8 },
    avgLifespan: { min: 10, max: 16 },
    size: "small",
    commonHealthIssues: ["호흡기 문제", "눈 질환", "피부 질환"],
    geneticConditions: ["신장 이형성증"],
    exerciseNeeds: "low",
    groomingNeeds: "high",
    dietaryConsiderations: ["비만 주의", "더위에 약함"],
  },
  {
    breed: "포메라니안",
    species: "dog",
    avgWeight: { min: 1.5, max: 3.5 },
    avgLifespan: { min: 12, max: 16 },
    size: "small",
    commonHealthIssues: ["슬개골 탈구", "기관허탈", "치과 질환"],
    geneticConditions: ["탈모증"],
    exerciseNeeds: "moderate",
    groomingNeeds: "high",
    dietaryConsiderations: ["소형견용 작은 알갱이"],
  },
  {
    breed: "골든 리트리버",
    species: "dog",
    avgWeight: { min: 25, max: 35 },
    avgLifespan: { min: 10, max: 12 },
    size: "large",
    commonHealthIssues: ["고관절 이형성증", "피부 알레르기", "귀 감염"],
    geneticConditions: ["암", "심장병"],
    exerciseNeeds: "high",
    groomingNeeds: "moderate",
    dietaryConsiderations: ["관절 건강 관리", "비만 주의"],
  },
  {
    breed: "진도개",
    species: "dog",
    avgWeight: { min: 18, max: 25 },
    avgLifespan: { min: 12, max: 15 },
    size: "medium",
    commonHealthIssues: ["갑상선 기능 저하증"],
    geneticConditions: [],
    exerciseNeeds: "high",
    groomingNeeds: "moderate",
    dietaryConsiderations: ["단백질 충분히"],
  },
  {
    breed: "웰시코기",
    species: "dog",
    avgWeight: { min: 10, max: 14 },
    avgLifespan: { min: 12, max: 14 },
    size: "medium",
    commonHealthIssues: ["추간판 질환", "고관절 이형성증", "비만"],
    geneticConditions: ["퇴행성 척수증"],
    exerciseNeeds: "high",
    groomingNeeds: "moderate",
    dietaryConsiderations: ["체중 관리 필수"],
  },
  {
    breed: "비글",
    species: "dog",
    avgWeight: { min: 9, max: 11 },
    avgLifespan: { min: 12, max: 15 },
    size: "medium",
    commonHealthIssues: ["귀 감염", "비만", "간질"],
    geneticConditions: ["뮤코다당증"],
    exerciseNeeds: "high",
    groomingNeeds: "low",
    dietaryConsiderations: ["식탐 주의", "체중 관리"],
  },
  {
    breed: "기타 (직접 입력)",
    species: "dog",
    avgWeight: { min: 1, max: 50 },
    avgLifespan: { min: 10, max: 15 },
    size: "medium",
    commonHealthIssues: [],
    geneticConditions: [],
    exerciseNeeds: "moderate",
    groomingNeeds: "moderate",
    dietaryConsiderations: [],
  },
]

export const CAT_BREEDS: BreedInfo[] = [
  {
    breed: "코리안 숏헤어",
    species: "cat",
    avgWeight: { min: 3, max: 5 },
    avgLifespan: { min: 15, max: 20 },
    size: "medium",
    commonHealthIssues: ["비만", "치과 질환"],
    geneticConditions: [],
    exerciseNeeds: "moderate",
    groomingNeeds: "low",
    dietaryConsiderations: ["비만 주의"],
  },
  {
    breed: "페르시안",
    species: "cat",
    avgWeight: { min: 3, max: 5.5 },
    avgLifespan: { min: 12, max: 17 },
    size: "medium",
    commonHealthIssues: ["호흡기 문제", "눈물자국", "피부 질환"],
    geneticConditions: ["다낭성 신장 질환"],
    exerciseNeeds: "low",
    groomingNeeds: "high",
    dietaryConsiderations: ["헤어볼 관리"],
  },
  {
    breed: "러시안 블루",
    species: "cat",
    avgWeight: { min: 3, max: 5.5 },
    avgLifespan: { min: 15, max: 20 },
    size: "medium",
    commonHealthIssues: ["비만", "방광 결석"],
    geneticConditions: [],
    exerciseNeeds: "moderate",
    groomingNeeds: "low",
    dietaryConsiderations: ["수분 섭취 중요"],
  },
  {
    breed: "브리티시 숏헤어",
    species: "cat",
    avgWeight: { min: 4, max: 8 },
    avgLifespan: { min: 12, max: 17 },
    size: "large",
    commonHealthIssues: ["비만", "치과 질환", "심장병"],
    geneticConditions: ["비대성 심근병증"],
    exerciseNeeds: "low",
    groomingNeeds: "moderate",
    dietaryConsiderations: ["체중 관리"],
  },
  {
    breed: "스코티시 폴드",
    species: "cat",
    avgWeight: { min: 3, max: 6 },
    avgLifespan: { min: 11, max: 14 },
    size: "medium",
    commonHealthIssues: ["관절 질환", "귀 질환"],
    geneticConditions: ["골연골이형성증"],
    exerciseNeeds: "low",
    groomingNeeds: "moderate",
    dietaryConsiderations: ["관절 건강 관리"],
  },
  {
    breed: "랙돌",
    species: "cat",
    avgWeight: { min: 4, max: 9 },
    avgLifespan: { min: 12, max: 17 },
    size: "large",
    commonHealthIssues: ["비대성 심근병증", "방광 결석"],
    geneticConditions: ["비대성 심근병증"],
    exerciseNeeds: "low",
    groomingNeeds: "high",
    dietaryConsiderations: ["헤어볼 관리"],
  },
  {
    breed: "뱅갈",
    species: "cat",
    avgWeight: { min: 4, max: 7 },
    avgLifespan: { min: 12, max: 16 },
    size: "medium",
    commonHealthIssues: ["소화기 문제"],
    geneticConditions: ["진행성 망막 위축"],
    exerciseNeeds: "high",
    groomingNeeds: "low",
    dietaryConsiderations: ["고단백 식이"],
  },
  {
    breed: "기타 (직접 입력)",
    species: "cat",
    avgWeight: { min: 2, max: 10 },
    avgLifespan: { min: 12, max: 18 },
    size: "medium",
    commonHealthIssues: [],
    geneticConditions: [],
    exerciseNeeds: "moderate",
    groomingNeeds: "moderate",
    dietaryConsiderations: [],
  },
]

export function getBreedInfo(
  breed: string,
  species: Species
): BreedInfo | undefined {
  const breeds = species === "dog" ? DOG_BREEDS : CAT_BREEDS
  return breeds.find((b) => b.breed === breed)
}

export function getBreedsBySpecies(species: Species): string[] {
  const breeds = species === "dog" ? DOG_BREEDS : CAT_BREEDS
  return breeds.map((b) => b.breed)
}
